import{S as L,i as d}from"./assets/vendor-BRQ76Mty.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const b="46051041-cf19ab3ef74349fd60d832ede",v="https://pixabay.com/api/";async function y(r,n=1){const o=await fetch(`${v}?key=${b}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`);if(!o.ok)throw new Error("Failed to fetch images");const s=await o.json();return{images:s.hits,totalHits:s.totalHits}}function m(r,n){const o=r.map(({webformatURL:s,largeImageURL:e,tags:t,likes:i,views:h,comments:w,downloads:E})=>`
        <div class="gallery-item">
            <a href="${e}" class="gallery-link">
                <img src="${s}" alt="${t}" loading="lazy" />
            </a>
            <div class="info">
                <p><strong>Likes:</strong> ${i}</p>
                <p><strong>Views:</strong> ${h}</p>
                <p><strong>Comments:</strong> ${w}</p>
                <p><strong>Downloads:</strong> ${E}</p>
            </div>
        </div>
    `).join("");n.innerHTML+=o}function S(r){r.innerHTML=""}function f(){document.getElementById("loader").style.display="flex"}function u(){document.getElementById("loader").style.display="none"}const $=document.querySelector("#search-form"),l=document.querySelector("#gallery"),c=document.querySelector("#load-more");let a=1,g="";const p=new L(".gallery a");$.addEventListener("submit",async r=>{r.preventDefault();const n=r.target.elements.query.value.trim();if(!n){d.error({title:"Error",message:"Search field cannot be empty!"});return}g=n,a=1,S(l),c.style.display="none",f();try{const{images:o,totalHits:s}=await y(g,a);if(o.length===0){d.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}m(o,l),p.refresh(),c.style.display="block";const e=Math.ceil(s/15);if(a>=e){c.style.display="none";const t=document.createElement("p");t.textContent="We're sorry, but you've reached the end of search results.",t.style.textAlign="center",l.appendChild(t)}}catch(o){d.error({title:"Error",message:"Something went wrong while fetching images."}),console.error("Error:",o)}finally{u()}});c.addEventListener("click",async()=>{a+=1,f();try{const{images:r,totalHits:n}=await y(g,a);m(r,l),p.refresh();const o=Math.ceil(n/15);if(a>=o){c.style.display="none";const e=document.createElement("p");e.textContent="We're sorry, but you've reached the end of search results.",e.style.textAlign="center",l.appendChild(e)}const s=document.querySelector(".gallery-item");if(s){const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}catch(r){d.error({title:"Error",message:"Failed to load more images."}),console.error("Error:",r)}finally{u()}});
//# sourceMappingURL=index.js.map
