import{a as E,S as b,i as d}from"./assets/vendor-imftU1ph.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const v="46051041-cf19ab3ef74349fd60d832ede",S="https://pixabay.com/api/";async function m(o,s=1){try{const r=await E.get(S,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}});return{images:r.data.hits,totalHits:r.data.totalHits}}catch{throw new Error("Не вдалося отримати зображення")}}function y(o,s){const r=o.map(({webformatURL:n,largeImageURL:e,tags:t,likes:i,views:h,comments:w,downloads:L})=>`
        <div class="gallery-item">
            <a href="${e}" class="gallery-link">
                <img src="${n}" alt="${t}" loading="lazy" />
            </a>
            <div class="info">
                <p><strong>Likes:</strong> ${i}</p>
                <p><strong>Views:</strong> ${h}</p>
                <p><strong>Comments:</strong> ${w}</p>
                <p><strong>Downloads:</strong> ${L}</p>
            </div>
        </div>
    `).join("");s.innerHTML+=r}function q(o){o.innerHTML=""}function f(){document.getElementById("loader").style.display="flex"}function u(){document.getElementById("loader").style.display="none"}const x=document.querySelector("#search-form"),l=document.querySelector("#gallery"),c=document.querySelector("#load-more");let a=1,g="";const p=new b(".gallery a");x.addEventListener("submit",async o=>{o.preventDefault();const s=o.target.elements.query.value.trim();if(!s){d.error({title:"Error",message:"Search field cannot be empty!"});return}g=s,a=1,q(l),c.style.display="none",f();try{const{images:r,totalHits:n}=await m(g,a);if(r.length===0){d.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}y(r,l),p.refresh(),c.style.display="block";const e=Math.ceil(n/15);if(a>=e){c.style.display="none";const t=document.createElement("p");t.textContent="We're sorry, but you've reached the end of search results.",t.classList.add("end-message"),t.style.textAlign="center",l.appendChild(t)}}catch(r){d.error({title:"Error",message:"Something went wrong while fetching images."}),console.error("Error:",r)}finally{u()}});c.addEventListener("click",async()=>{a+=1,f();try{const{images:o,totalHits:s}=await m(g,a);y(o,l),p.refresh();const r=Math.ceil(s/15);if(a>=r){c.style.display="none";const e=document.createElement("p");e.textContent="We're sorry, but you've reached the end of search results.",e.classList.add("end-message"),e.style.textAlign="center",l.appendChild(e)}const n=document.querySelector(".gallery-item");if(n){const{height:e}=n.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}catch(o){d.error({title:"Error",message:"Failed to load more images."}),console.error("Error:",o)}finally{u()}});
//# sourceMappingURL=index.js.map
